### ISSUE TITLE
Improve formatting / methods of `Switches`

### ISSUE THREAD

**Issue by adracus** [onmetal/controller-utils#36]
# Summary

When working with `Switches`, I discovered multiple issues we should resolve:
1. The `Type()` of `Switches` should be `strings`.
2. The `String()` method of `Switches` is not nice: It currently prints the map like `map[string]bool{foo: true, bar: true}`. This should be formatted better.
3. The function `NewSwitches` should be renamed to `New`. Additionally, there should be a method called `Make` that does the same but returns `Switches` instead of `*Switches`. This improves ease of use in literals.
4. There should be a possibility to disable all items. Double check this with how k8s does it in e.g. `kube-controller-manager`'s `controllers`.
5. There should be a method returning a `sets.String` of the currently enabled items (`EnabledByDefault`?).

**Comment by GrigoriyMikhalkin** [comment]
@adracus Do you have an idea how to print contents of `Switches` better? 

I'm currently thinking about printing it as:
```
foo: enabled
bar: disabled
```

Does it look good?

**Comment by adracus** [comment]
Considering we'll have a lot of switches, this will be too bloated.
I'd propose the same 'syntax' as if you'd enable them by hand:
`controller1,controller2,-controller3`
